version: 1.0.{build}
branches:
  only:
  - master
os:
  - Visual Studio 2017
assembly_info:
  patch: true
  file: '**\FelineSorter.csproj'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
configuration: Release
before_build: 
  - dotnet restore FelineSorter.sln
test_script:
  - dotnet test .\FelineSorter.UnitTests\FelineSorter.UnitTests.csproj